# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1ae260f24a4e2abe53ef29e56449331a71087bc0dcb3d64d95ef8ce262a4a7c32afa02eeefe84cd25c9bb85b4a22534ebe3a6fd60cabd87f5ced6f7181ca11

test:
  secret_key_base: 1724df5d11bec88126adef67862c475413dc8a05bc9aaeb79b6e71dd88f118e8c2283d1fc344ddb3d1561518125559191df3a84e2818509573bb0e2642428315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
